# Generated by Django 6.0.7 on 2026-09-01 18:10

import users.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined',
            field=models.DateField(default=users.models.user.current_month_joined),
        ),
    ]
