# Generated by Django 6.0.7 on 2026-09-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='vehicle_photos/')),
                ('engine', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=255)),
                ('body_type', models.CharField(blank=True, choices=[('Truck', 'Truck'), ('SUV', 'Suv'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Minivan', 'Minivan'), ('Hatchback', 'Hatchback'), ('Wagon', 'Wagon')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sold', models.BooleanField(default=False)),
                ('milage', models.PositiveIntegerField()),
                ('deal', models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('bad', 'Bad')], max_length=10)),
                ('vehicle', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.vehicle')),
            ],
        ),
    ]
