# Generated by Django 6.0.7 on 2026-07-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Truck', 'Truck'), ('SUV', 'Suv'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Minivan', 'Minivan'), ('Hatchback', 'Hatchback'), ('Wagon', 'Wagon')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='deal',
            field=models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('bad', 'Bad')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=255),
        ),
    ]
