# Generated by Django 6.0.7 on 2026-08-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_photo_options_vehicle_body_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='vehicle',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.vehicle'),
        ),
    ]
